#!/usr/bin/env python3
"""Generate CSS custom properties from the Figma variable export.

Three layers, mirroring the Figma collections exactly:
  1. Primitives  — one block per theme          -> [data-theme="..."]
  2. Semantic    — aliases into primitives      -> [data-appearance="light|dark"]
  3. Breakpoint  — type scale and grid metrics  -> :root + media queries

Run: python3 tokens/build_tokens.py
Writes: src/styles/tokens.css
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "tokens" / "figma-tokens.json").read_text())


def slug(s):
    out = []
    for ch in s.lower():
        out.append(ch if ch.isalnum() else "-")
    return "".join(out).strip("-").replace("---", "-").replace("--", "-")


def num(v):
    """Emit 24 not 24.0, and keep 15.5 intact."""
    return str(int(v)) if float(v) == int(v) else str(v)


def primitives():
    t = DATA["theme"]
    out = []
    for i, mode in enumerate(t["modes"]):
        sel = f':root, [data-theme="{slug(mode)}"]' if i == 0 else f'[data-theme="{slug(mode)}"]'
        out.append(f"\n{sel} {{")
        for name, vals in t["v"].items():
            out.append(f"  --p-{slug(name)}: #{vals[i]};")
        out.append("}")
    return out


def semantic():
    a = DATA["appearance"]
    out = []
    for i, mode in enumerate(a["modes"]):
        sel = ':root, [data-appearance="light"]' if i == 0 else '[data-appearance="dark"]'
        out.append(f"\n{sel} {{")
        for name, vals in a["v"].items():
            out.append(f"  --c-{slug(name)}: var(--p-{slug(vals[i])});")
        for name, src in a["derived"].items():
            out.append(f"  --c-{slug(name)}: var(--c-{slug(src)});")
        out.append("}")

    # Respect the OS preference when the page has not been explicitly set.
    out.append("\n@media (prefers-color-scheme: dark) {")
    out.append("  :root:not([data-appearance]) {")
    for name, vals in a["v"].items():
        out.append(f"    --c-{slug(name)}: var(--p-{slug(vals[1])});")
    for name, src in a["derived"].items():
        out.append(f"    --c-{slug(name)}: var(--c-{slug(src)});")
    out.append("  }\n}")
    return out


def breakpoints():
    b = DATA["breakpoint"]
    unitless = {"Grid/Columns"}
    out = []
    for i, query in enumerate(b["queries"]):
        body = []
        for name, vals in b["v"].items():
            unit = "" if name in unitless else "px"
            body.append(f"  --{slug(name)}: {num(vals[i])}{unit};")
        if query is None:
            out.append("\n:root {\n" + "\n".join(body) + "\n}")
        else:
            inner = "\n".join("  " + line for line in body)
            out.append(f"\n@media {query} {{\n  :root {{\n{inner}\n  }}\n}}")
    return out


def statics():
    out = ["\n:root {"]
    for k, v in DATA["spacing"].items():
        out.append(f"  --space-{k}: {num(v)}px;")
    f = DATA["fonts"]
    out.append(f'  --font-primary: "{f["primary"]}", "Jost", "Century Gothic", sans-serif;')
    out.append(f'  --font-secondary: "{f["secondary"]}", "Bodoni Moda", Didot, Georgia, serif;')
    out.append(f'  --font-body: "{f["body"]}", "Source Sans 3", system-ui, sans-serif;')
    out.append("}")
    return out


WEIGHTS = {  # Futura PT / Merriweather Sans named weights -> numeric
    "Book": 400, "Light": 300, "Regular": 400, "Medium": 500,
    "Demi": 600, "Bold": 700, "Heavy": 800,
    "Display Demi": 600, "Subhead Regular": 400, "Subhead Italic": 400,
}


def text_styles():
    """One class per Figma text style, sized from the breakpoint tokens."""
    out = []
    for s in DATA["textStyles"]:
        cls = ".t-" + slug(s["name"])
        tok = slug(s["token"])
        out.append(f"\n{cls} {{")
        out.append(f"  font-family: var(--font-{s['font']});")
        out.append(f"  font-weight: {WEIGHTS.get(s['weight'], 400)};")
        if s.get("italic"):
            out.append("  font-style: italic;")
        out.append(f"  font-size: var(--type-{tok}-size);")
        out.append(f"  line-height: var(--type-{tok}-line-height);")
        tr = s["tracking"]
        if tr not in ("0", "0%"):
            out.append(f"  letter-spacing: {float(tr.rstrip('%')) / 100:.4f}em;")
        if s["case"] == "upper":
            out.append("  text-transform: uppercase;")
        out.append("}")
    return out


def main():
    lines = [
        "/* NID design tokens.",
        " * Generated by tokens/build_tokens.py from tokens/figma-tokens.json,",
        " * which is exported from the Figma variable collections. Do not hand-edit.",
        " */",
    ]
    lines += ["\n/* ---- 1. Primitives: one ramp set per theme ---- */"] + primitives()
    lines += ["\n/* ---- 2. Static scales ---- */"] + statics()
    lines += ["\n/* ---- 3. Semantic colour: light and dark ---- */"] + semantic()
    lines += ["\n/* ---- 4. Breakpoint scale: type and grid ---- */"] + breakpoints()
    lines += ["\n/* ---- 5. Text styles ---- */"] + text_styles()

    dest = ROOT / "src" / "styles" / "tokens.css"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n")

    themes = len(DATA["theme"]["modes"])
    print(f"tokens.css written: {len(DATA['theme']['v'])} primitives x {themes} themes, "
          f"{len(DATA['appearance']['v']) + len(DATA['appearance']['derived'])} semantic, "
          f"{len(DATA['breakpoint']['v'])} breakpoint vars x 4 modes, "
          f"{len(DATA['textStyles'])} text styles -> {dest.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
